intents:
  dance.start:
    - "춤춰줘"
  camera.capture:
    - "사진 찍어줘"
  ui.game_mode.enter:
    - "게임 모드"
  timer.create:
    - "분 뒤에 알려줘"
    - "초 뒤에 알려줘"
  weather.current:
    - "날씨 알려줘"
  smarthome.aircon.on:
    - "에어컨 켜줘"
  smarthome.aircon.off:
    - "에어컨 꺼줘"
  smarthome.heater.on:
    - "난방 켜줘"
  smarthome.heater.off:
    - "난방 꺼줘"
  smarthome.light.on:
    - "거실 등 켜줘"
  smarthome.light.off:
    - "거실 등 꺼줘"
  smarthome.indirect_light.on:
    - "간접등 켜줘"
  smarthome.indirect_light.off:
    - "간접등 꺼줘"
  smarthome.robot_cleaner.start:
    - "청소기 돌려줘"
  smarthome.robot_cleaner.stop:
    - "청소기 정지"
  smarthome.air_purifier.on:
    - "공기청정기 켜줘"
  smarthome.air_purifier.off:
    - "공기청정기 꺼줘"
  smarthome.tv.on:
    - "티비 켜줘"
  smarthome.tv.off:
    - "티비 꺼줘"
  smarthome.computer.on:
    - "컴퓨터 켜줘"
  smarthome.computer.off:
    - "컴퓨터 꺼줘"
  smarthome.music.play:
    - "음악 틀어줘"
  smarthome.music.stop:
    - "음악 꺼줘"
  smarthome.all.off:
    - "다 꺼줘"
  system.ack:
    - "확인"
  system.cancel:
    - "취소"
